name: alliemillerdesignsbeta
favicon: null
layout_spectrum: 0.51541
typography_spectrum: 0.87958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d4d8'
    - '#7e9fba'
    - '#f55e20'
    - '#f4d330'
    - '#563930'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
